flattening and out dir

diff --git a/grab b/grab
--- a/grab
+++ b/grab
@@ -1,6 +1,6 @@
 #!/bin/env bash
 
-VER="0.2.7"
+VER="0.2.8"
 
 GR="\033[0;36m"
 RD="\033[0;31m"
@@ -69,23 +69,28 @@ cd ${tmpf}
 
 msg "Downloading ${a} from github.com/${u}" 
 wget -qN "https://github.com/${u}/releases/latest/download/${a}"
-[ $? -ne 0 ] && { err "unable to download https://github.com/${u}/releases/latest/download/${a}"; exit 1; }
+[ $? -ne 0 ] && { err "Unable to download https://github.com/${u}/releases/latest/download/${a}"; exit 1; }
 
-[ -f ${a} ] || { err "file ${a} not found"; rm -rf ${tmpf}; exit 1; }
+[ -f ${a} ] || { err "File ${a} not found in ${tmpf}"; rm -rf ${tmpf}; exit 1; }
 
 ext="${a##*.}"
 msg "Archive type is ${ext}"
 
-msg "Extracting ${e} from ${a} into ${tmpf}"
+od="${tmpf}/out"
+msg "Extracting ${e} from ${a} into ${od}"
 
 if [ $ext == "zip" ]; then
-    unzip -oq ${a}
+    unzip -oq ${a} -d ${od}
+    [ -f ${od}/${e} ] || { ls -lh ${od}; warn "Unable to find ${e}, flattening..."; rm -rf ${od}; mkdir -p ${od}; unzip -oqj ${a} -d ${od}; }
+    [ -f ${od}/${e} ] || { ls -lh ${od}; err "Unable to find ${e}, giving up."; rm -rf ${tmpf}; exit 1; }
 elif [ $ext == "gz" ]; then
-    tar -xzf ${a}
-    [ -f ${e} ] || { warn "Unable to find ${e}, flattening 1 level..."; tar -xzf ${a} --strip-components 1; }
-    [ -f ${e} ] || { warn "Unable to find ${e}, flattening 2 levels..."; tar -xzf ${a} --strip-components 2; }
-    [ -f ${e} ] || { warn "Unable to find ${e}, flattening 3 levels..."; tar -xzf ${a} --strip-components 3; }
-    [ -f ${e} ] || { err "Unable to find ${e}, giving up."; rm -rf ${tmpf}; exit 1; }
+    mkdir -p ${od}
+    [ -d ${od} ] || { err "Failed to create output directory ${od}"; rm -rf ${tmpf}; exit 1; }
+    tar -xzf ${a} -C ${od}
+    [ -f ${od}/${e} ] || { ls -lh ${od}; warn "Unable to find ${od}/${e}, flattening 1 level..."; rm -rf ${od}; mkdir -p ${od}; tar -xzf ${a} --strip-components 1 -C ${od}; }
+    [ -f ${od}/${e} ] || { ls -lh ${od}; warn "Unable to find ${od}/${e}, flattening 2 levels..."; rm -rf ${od}; mkdir -p ${od}; tar -xzf ${a} --strip-components 2 -C ${od}; }
+    [ -f ${od}/${e} ] || { ls -lh ${od}; warn "Unable to find ${od}/${e}, flattening 3 levels..."; rm -rf ${od}; mkdir -p ${od};  tar -xzf ${a} --strip-components 3 -C ${od}; }
+    [ -f ${od}/${e} ] || { ls -lh ${od}; err "Unable to find ${od}/${e}, giving up."; rm -rf ${tmpf}; exit 1; }
 else
     err "Unable to extract from ${ext}"
     rm -rf ${tmpf}
@@ -94,18 +99,18 @@ fi
 [ $? -ne 0 ] && { err "Unable to unzip ${a}"; rm -rf ${tmpf}; exit 1; }
 
 msg "Making ${e} executable..."
-chmod +x ${e} 
+chmod +x ${od}/${e} 
 
 [ $? -ne 0 ] && { err "Unable to make ${e} executable"; rm -rf ${tmpf}; exit 1; }
 
 msg "Installing ${e} to /usr/local/bin..."
-sudo mv ${e} /usr/local/bin
+sudo mv ${od}/${e} /usr/local/bin
 
 [ -f /usr/local/bin/${e} ] || { err "failed to install ${e}"; rm -rf ${tmpf}; exit 1; }
 
 msg "Successfully installed!\n"
 
-warn "To uninstall: rm -f /usr/local/bin/${e}"
+warn "To uninstall: sudo rm -f /usr/local/bin/${e}"
 
 msg "\nDeleting ${tmpf} and cleaning up..."
 rm -rf ${tmpf}
