aesthetics

diff --git a/grab b/grab
--- a/grab
+++ b/grab
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VER="0.2.5"
+VER="0.2.6"
 
 GR="\033[0;36m"
 RD="\033[0;31m"
@@ -19,7 +19,7 @@ function err {
     echo -e "$RD${1}$OF"
 }
 
-msg "\ngrab version ${VER}"
+msg "\nGRAB✊version ${VER}"
 msg "platform: ${OSTYPE}"
 
 command -v wget >/dev/null 2>&1 || { err "wget not installed"; exit 1;} 
@@ -47,63 +47,64 @@ lst=$(curl -s "https://api.github.com/repos/${u}/releases/latest" \
 
 [ $? -ne 0 ] && { err "unable to find eligible files in the latest release of this repository"; exit 1; }
 
-echo -e "\nchoose the version you would like to install:\n"
+echo -e "\n👉 Choose the version you would like to install:\n"
 select choice in ${lst}; do
     if [[ -n $choice ]]; then
         a="${choice}"
         msg "\nYou chose to install ${a}"
         break
     else
-        err "invalid choice, try again"
+        err "Invalid choice, try again"
     fi
 done
 
 
 tmpf="/tmp/grab_cache_$$"
-msg "creating cache in ${tmpf}"
+msg "Creating cache in ${tmpf}"
 mkdir "${tmpf}"
 
 [ -d "${tmpf}" ] || { err "failed to create cache folder ${tmpf}"; exit 1; }
 
 cd ${tmpf}
 
-msg "downloading ${a} from github.com/${u}" 
+msg "Downloading ${a} from github.com/${u}" 
 wget -qN "https://github.com/${u}/releases/latest/download/${a}"
 [ $? -ne 0 ] && { err "unable to download https://github.com/${u}/releases/latest/download/${a}"; exit 1; }
 
 [ -f ${a} ] || { err "file ${a} not found"; rm -rf ${tmpf}; exit 1; }
 
 ext="${a##*.}"
-msg "archive type is ${ext}"
+msg "Archive type is ${ext}"
 
-msg "extracting ${e} from ${a}..."
+msg "Extracting ${e} from ${a} into ${tmpf}"
 
 if [ $ext == "zip" ]; then
     unzip -oq ${a}
 elif [ $ext == "gz" ]; then
     tar -xzf ${a} --strip-components 1
 else
-    err "unable to extract from ${ext}"
+    err "Unable to extract from ${ext}"
     rm -rf ${tmpf}
 fi
 
-[ $? -ne 0 ] && { err "unable to unzip ${a}"; rm -rf ${tmpf}; exit 1; }
+[ $? -ne 0 ] && { err "Unable to unzip ${a}"; rm -rf ${tmpf}; exit 1; }
 
 
-msg "installing ${e} to /usr/local/bin..."
+msg "Installing ${e} to /usr/local/bin..."
 chmod +x ${e} 
 sudo mv ${e} /usr/local/bin
 
 [ -f /usr/local/bin/${e} ] || { err "failed to install ${e}"; rm -rf ${tmpf}; exit 1; }
 
-msg "successfully installed"
-warn "to uninstall: rm -f /usr/local/bin/${e}"
+msg "Successfully installed\n"
 
-msg "cleaning up..."
+warn "To uninstall: rm -f /usr/local/bin/${e}"
+
+msg "\nDeleting ${tmpf} and cleaning up..."
 rm -rf ${tmpf}
 
-[ -d "${tmpf}" ] && { err "failed to delete cache folder ${tmpf}"; exit 1; }
+[ -d "${tmpf}" ] && { err "Failed to delete cache folder ${tmpf}"; exit 1; }
 
-msg "~*~ done\n"
+msg "done 👍\n"
 
 
